### ISSUE TITLE
This project may no longer be necessary

### ISSUE THREAD

**Issue by stevenvachon** [maltsev/posthtml-inline-css#14]
Gmail now supports `<style>`
https://litmus.com/blog/gmail-to-support-responsive-email-design

**Comment by maltsev** [comment]
Good to know. Thanks for the article!

Though, there are many email clients around the world, where CSS inlining is still necessary.

**Comment by stevenvachon** [comment]
Possibly, but according to https://www.campaignmonitor.com/css/, only Gmail needed it.

**Comment by cossssmin** [comment]
### 2020 update

While the vast majority of email clients now support CSS in a `<style>` tag inside the `<head>`, there is still one major issue: multiple classes and Outlook on Windows.

The problem is Outlook on Windows, with its Word rendering engine, will only read and apply the _first_ class it encounters in a `class=""` attribute, discarding anything after it.

For example this:

```html
<!DOCTYPE html>
<html>
<head>
  <style>
    .uppercase {text-transform: uppercase}
    .text-red {color: red}
  </style>
</head>
<body>
  <p class="uppercase text-red">Test</p>
</body>
```

Will render as black, uppercased text in Outlook on Windows (2007-2019) - the `text-red` class will _not_ be applied.

Currently, the only way around this for Outlook on Windows is to always use a single class:

```html
<!DOCTYPE html>
<html>
<head>
  <style>
    .content {
      text-transform: uppercase; 
      color: red;
    }
  </style>
</head>
<body>
  <p class="content">Test</p>
</body>
```

... or to inline the CSS 🤷‍♂️

**Comment by maltsev** [comment]
I added a link to this discussion to `README.md`, so a developer could decide themselves whether they need CSS inlining or not.
